# -*- conf -*-

# Default values and options can be found using man 5 foot.ini.

font=monospace:size=10
dpi-aware=yes

# include=/usr/share/foot/themes/dracula
include=/home/max/.config/foot/themes/srcery.ini
